# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Caddyfile.conf                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tissad <tissad@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/23 20:42:45 by tissad            #+#    #+#              #
#    Updated: 2025/01/24 16:52:10 by tissad           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
#                                CADDY CONFIGURATION                           #
# **************************************************************************** # 


{
    auto_https off  # Désactiver HTTPS automatique si vous n'avez pas de domaine
}

:8080 {
    root * /var/www/html # Répertoire où se trouvent les fichiers statiques
    file_server  # Active le serveur de fichiers statiques

    # Activer la compression pour améliorer les performances
    encode gzip zstd
}
