# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql.conf                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tissad <tissad@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/23 20:42:45 by tissad            #+#    #+#              #
#    Updated: 2025/03/25 14:01:21 by tissad           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
#                               MARIADB CONFIGURATION                          #
# **************************************************************************** # 
[mysqld]
user=mysql
datadir=/var/lib/mysql
socket=/run/mysqld/mysqld.sock
bind-address=0.0.0.0
log_error=mariadb.log

# Optimisations
skip-host-cache
skip-name-resolve
#query_cache_size = 16M
#query_cache_type = 1
#query_cache_limit = 2M
#max_connections = 151
#thread_cache_size = 38
#open_files_limit = 65535
#table_definition_cache = 600
#table_open_cache = 2000
#*****************************************************************************#
